# MSCI Indonesian Stocks
A Python script to monitor MSCI stocks performance by comparing the current market price against predefined base and support levels.

In [1]:
import yfinance as yf
import pandas as pd

In [2]:
def analyze_stocks(list_A, base_A, support_A):
    # Download last closing prices
    data = yf.download(list_A, period="1d", progress=False)
    closing = data['Close'].iloc[-1]

    # Ensure correct order of closing prices
    last_A = [closing[ticker] for ticker in list_A]

    # Create DataFrame
    stocks_A = pd.DataFrame({
        'Stock': list_A,
        'Base': base_A,
        'Support': support_A,
        'Last Price': last_A})
    
    stocks_A['Change from Base (%)'] = (stocks_A['Last Price'] - stocks_A['Base'])/stocks_A['Base']*100
    stocks_A['Change from Support (%)'] = (stocks_A['Last Price'] - stocks_A['Support'])/stocks_A['Support']*100

    # Styling function
    def color_change(val):
        color = 'green' if val > 0 else 'red'
        return f'color: {color}'

    # Return styled DataFrame
    styled_stocks_A = stocks_A.style \
        .map(color_change, subset=['Change from Base (%)', 'Change from Support (%)']) \
        .format({
            'Last Price': '{:.0f}',
            'Change from Base (%)': '{:.2f}',
            'Change from Support (%)': '{:.2f}'})
    return styled_stocks_A

In [3]:
def analyze_stocks_realtime(list_A, base_A, support_A):
    # Get realtime prices using .fast_info['lastPrice']
    last_A = []
    for ticker in list_A:
        try:
            stock = yf.Ticker(ticker)
            last_price = stock.fast_info['lastPrice']
        except Exception:
            last_price = None
        last_A.append(last_price)

    # Create DataFrame
    stocks_A = pd.DataFrame({
        'Stock': list_A,
        'Base': base_A,
        'Support': support_A,
        'Last': last_A})

    # Create DataFrame
    stocks_A = pd.DataFrame({
        'Stock': list_A,
        'Base': base_A,
        'Support': support_A,
        'Last Price': last_A})
    
    stocks_A['Change from Base (%)'] = (stocks_A['Last Price'] - stocks_A['Base'])/stocks_A['Base']*100
    stocks_A['Change from Support (%)'] = (stocks_A['Last Price'] - stocks_A['Support'])/stocks_A['Support']*100

    # Styling function
    def color_change(val):
        color = 'green' if val > 0 else 'red'
        return f'color: {color}'

    # Return styled DataFrame
    styled_stocks_A = stocks_A.style \
        .map(color_change, subset=['Change from Base (%)', 'Change from Support (%)']) \
        .format({
            'Last Price': '{:.0f}',
            'Change from Base (%)': '{:.2f}',
            'Change from Support (%)': '{:.2f}'})
    return styled_stocks_A

# My Stocks

In [4]:
# My Stocks
list_A = ["BBCA.JK", "BBRI.JK", "BMRI.JK", "BBNI.JK", "TLKM.JK", "ASII.JK", "PTBA.JK"]
base_A = [7400, 3360, 4350, 3670, 2310, 4430, 2300]
support_A = [8275, 3650, 4510, 3950, 2630, 4690, 2390]

stocks_A = analyze_stocks(list_A, base_A, support_A)
stocks_A

/var/folders/h9/3814k15d6g9gqm3g5762t5g40000gn/T/ipykernel_4116/49570061.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(list_A, period="1d", progress=False)

In [5]:
# Trading
list_B = ["AADI.JK", "ADMR.JK", "ADRO.JK", "AKRA.JK", "ASRI.JK", "AVIA.JK", "BBTN.JK", "BNGA.JK", "BRIS.JK", "BSDE.JK", "CDIA.JK", "CMRY.JK", "DKHH.JK", "PGAS.JK", "PTRO.JK", "ROTI.JK", "SRTG.JK", "WIFI.JK"]
base_B = [5750, 700, 1615, 895, 97, 342, 770, 1590, 2040, 725, 1485, 4030, 54, 1445, 1875, 795, 1225, 370]
support_B = [6700, 920, 1735, 1155, 121, 420, 1080, 1660, 2410, 780, 1485, 4530, 61, 1530, 2540, 795, 1560, 1985]

stocks_B = analyze_stocks(list_B, base_B, support_B)
stocks_B

/var/folders/h9/3814k15d6g9gqm3g5762t5g40000gn/T/ipykernel_4116/49570061.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(list_A, period="1d", progress=False)

## Watchlist

In [6]:
# Trading
list_C = ["PGEO.JK", "MDKA.JK", "INCO.JK",]
base_C = [730, 1035, 1845, ]
support_C = [1320, 1800, 3090]

stocks_C = analyze_stocks(list_C, base_C, support_C)
stocks_C

/var/folders/h9/3814k15d6g9gqm3g5762t5g40000gn/T/ipykernel_4116/49570061.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(list_A, period="1d", progress=False)